### ISSUE TITLE
User has accepted CLA, but their Pull Requests show as Not All Signed

### ISSUE THREAD

**Issue by thepag** [clahub/clahub#89]
Our [CLA](https://www.clahub.com/agreements/happyworm/jPlayer) asks for a *name* and *email*.

The user in question said that the `email` they used was not the same as their github username email. I have no idea if this is a cause, but I agree with the user that they should be able to put in any email address they want in there or it should state: **github username email**

The discussion thread is here: happyworm/jPlayer/pull/213

A number of users signed successfully before this failure, and one has signed afterwards and that worked fine too.

**Comment by SirCmpwn** [comment]
Reproduced here: https://github.com/SirCmpwn/TrueCraft/pull/18

**Comment by Nijikokun** [comment]
It is an issue with the **github user email** being private

**Comment by mzagaja** [comment]
After reading the code and testing it on a repo I don't think this bug is still in the code base (if it existed) as I set my GitHub e-mail to private and submitted a PR to one of my repos and had no issue passing. I also set the e-mail I signed with to a non-GitHub e-mail and it still passed. So going to close as non-reproducible. If this persists in another scenario I'm happy to re-visit.
